### ISSUE TITLE
e621 pool tracker

### ISSUE THREAD

**Issue by EpsiRho** [EpsiRho/YifferXYZ-Moderation-Panel-for-Windows#4]
## Idea 
I want a page where you can add e621 pools (and maybe others like fur affinity) and the app can tell you when new pages have been added

## Implementation
- [ ] A page where you can add pools and see your currently saved pools. 
- [ ] The app saves the pool id and the number of pages in the pool to a file. 
- [ ] When loading the page the app checks the saved number of pages vs the current number to tell if new pages have been added. 
- [ ] Link the pools to comics on yiffer, and make an easy "Update" button that can add new pages not currently on yiffer
- [ ] A card should be available for the homepage to show a few of the latest updated pools if any
